---
base: ../prefetch-dependencies/prefetch-dependencies.yaml
add:
  - use-source
  - create-source
  - create-prefetch
additionalSteps:
  - at: 0
    name: skip-ta
    image: quay.io/konflux-ci/task-runner:2.0.0@sha256:4b01fbf98fa7155f5c21443c285f88853864ae7cc66981cf6b543fc6ba16b81b
    when:
      - input: $(params.input)
        operator: in
        values: [""]
    env:
      - name: SOURCE_ARTIFACT
        value: $(params.SOURCE_ARTIFACT)
    computeResources:
      limits:
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
    script: |
      #!/bin/bash

      echo -n "${SOURCE_ARTIFACT}" > "$(results.SOURCE_ARTIFACT.path)"
      echo -n "" > "$(results.PREFETCH_ARTIFACT.path)"
stepWhen:
  use-trusted-artifact:
    - input: $(params.input)
      operator: notin
      values: [""]
  create-trusted-artifact:
    - input: $(params.input)
      operator: notin
      values: [""]
preferStepTemplate: true
removeWorkspaces:
  - source
replacements:
  workspaces.source.path: /var/workdir
useTAVolumeMount: true
