---
base: ../buildah/buildah.yaml
removeParams:
  - BUILDER_IMAGE
add:
  - use-source
  - use-prefetch
newPrefetchNaming: true
removeWorkspaces:
  - source
useTAVolumeMount: true
replacements:
  workspaces.source.path: /var/workdir
regexReplacements:
  "/workspace(/.*)": /var/workdir$1
